import type { JobApplication } from './types'

export const mockApplications: JobApplication[] = [
  {
    id: 'app-001',
    name: 'สมชาย ใจดี',
    phone: '081-234-5678',
    email: 'somchai@email.com',
    position: 'ช่างเทคนิค',
    jobType: 'fulltime',
    workMode: 'onsite',
    experience: '3 ปี ในงานซ่อมบำรุงเครื่องจักร',
    preferredTime: 'เช้า (08:00–12:00)',
    appliedAt: '2026-06-04',
    status: 'pending',
    notes: '',
  },
  {
    id: 'app-002',
    name: 'สุดา รักงาน',
    phone: '089-876-5432',
    email: 'suda@email.com',
    position: 'ฝ่ายการตลาด',
    jobType: 'fulltime',
    workMode: 'online',
    experience: '2 ปี ด้าน Digital Marketing',
    preferredTime: 'บ่าย (13:00–17:00)',
    appliedAt: '2026-06-01',
    status: 'reviewing',
    notes: 'มีประสบการณ์ด้าน SEO และ Social Media',
  },
  {
    id: 'app-003',
    name: 'วิชัย มุ่งมั่น',
    phone: '062-111-2222',
    email: 'wichai@email.com',
    position: 'Sale Executive',
    jobType: 'fulltime',
    workMode: 'onsite',
    experience: '5 ปี ในงานขายและการตลาด B2B',
    preferredTime: 'เช้า (08:00–12:00)',
    appliedAt: '2026-05-28',
    status: 'interviewing',
    notes: 'นัดสัมภาษณ์วันที่ 10 มิ.ย. 2026',
  },
  {
    id: 'app-004',
    name: 'มาลี สวยงาม',
    phone: '093-333-4444',
    email: 'malee@email.com',
    position: 'Customer Service',
    jobType: 'parttime',
    workMode: 'online',
    experience: '1 ปี ด้านบริการลูกค้า',
    preferredTime: 'เย็น (17:00–20:00)',
    appliedAt: '2026-05-25',
    status: 'rejected',
    notes: 'ไม่ตรงกับตำแหน่งที่เปิดรับ',
  },
  {
    id: 'app-005',
    name: 'ประสิทธิ์ เก่งกาจ',
    phone: '064-555-6666',
    email: 'prasit@email.com',
    position: 'ช่างเทคนิค',
    jobType: 'fulltime',
    workMode: 'onsite',
    experience: '7 ปี ในงานบำรุงรักษาระบบน้ำ',
    preferredTime: 'เช้า (08:00–12:00)',
    appliedAt: '2026-05-20',
    status: 'reviewing',
    notes: '',
  },
  {
    id: 'app-006',
    name: 'นิภา ขยันดี',
    phone: '085-777-8888',
    email: 'nipha@email.com',
    position: 'ฝ่ายบัญชี',
    jobType: 'fulltime',
    workMode: 'onsite',
    experience: '4 ปี ด้านบัญชีและการเงิน',
    preferredTime: 'บ่าย (13:00–17:00)',
    appliedAt: '2026-05-18',
    status: 'pending',
    notes: '',
  },
  {
    id: 'app-007',
    name: 'ธนากร พัฒนา',
    phone: '091-999-0000',
    email: 'thanakorn@email.com',
    position: 'Sale Executive',
    jobType: 'fulltime',
    workMode: 'onsite',
    experience: '2 ปี ในธุรกิจเครื่องดื่ม',
    preferredTime: 'เช้า (08:00–12:00)',
    appliedAt: '2026-05-15',
    status: 'interviewing',
    notes: 'นัดสัมภาษณ์วันที่ 8 มิ.ย. 2026',
  },
  {
    id: 'app-008',
    name: 'กานต์ดา ใหม่สด',
    phone: '082-123-9876',
    email: 'kanda@email.com',
    position: 'Customer Service',
    jobType: 'parttime',
    workMode: 'online',
    experience: 'ไม่มีประสบการณ์ แต่มีความกระตือรือร้น',
    preferredTime: 'เย็น (17:00–20:00)',
    appliedAt: '2026-05-10',
    status: 'pending',
    notes: '',
  },
  {
    id: 'app-009',
    name: 'อดิศักดิ์ ชำนาญ',
    phone: '076-654-3210',
    email: 'adisak@email.com',
    position: 'ช่างเทคนิค',
    jobType: 'fulltime',
    workMode: 'onsite',
    experience: '10 ปี ในงานซ่อมบำรุงตู้กาแฟและตู้น้ำ',
    preferredTime: 'เช้า (08:00–12:00)',
    appliedAt: '2026-05-05',
    status: 'rejected',
    notes: 'ต้องการเงินเดือนสูงกว่าอัตราที่เปิดรับ',
  },
  {
    id: 'app-010',
    name: 'ปริยา รอบรู้',
    phone: '098-246-8100',
    email: 'pariya@email.com',
    position: 'ฝ่ายการตลาด',
    jobType: 'fulltime',
    workMode: 'online',
    experience: '3 ปี ด้าน Content Marketing และ Graphic Design',
    preferredTime: 'บ่าย (13:00–17:00)',
    appliedAt: '2026-04-30',
    status: 'reviewing',
    notes: 'Portfolio น่าสนใจมาก',
  },
]
