import type { PortfolioItem } from './types'

export const mockPortfolio: PortfolioItem[] = [
  {
    id: 'port-001',
    name: '7-Eleven สาขาลาดพร้าว',
    type: 'water',
    location: 'ลาดพร้าว กรุงเทพมหานคร',
    machineCount: 2,
    installDate: '2024-01-15',
    status: 'published',
    description: 'ติดตั้งตู้น้ำดื่มหยอดเหรียญ 2 ตู้ บริเวณหน้าร้านและในร้าน ลูกค้าใช้บริการเฉลี่ย 150 ครั้ง/วัน',
  },
  {
    id: 'port-002',
    name: 'Big C สาขารามอินทรา',
    type: 'mixed',
    location: 'รามอินทรา กรุงเทพมหานคร',
    machineCount: 4,
    installDate: '2024-02-20',
    status: 'published',
    description: 'ติดตั้งตู้น้ำ 2 ตู้ และตู้น้ำแข็ง 2 ตู้ ในพื้นที่ห้างสรรพสินค้า ยอดขายสูงสุดในพอร์ตโฟลิโอ',
  },
  {
    id: 'port-003',
    name: 'หมู่บ้านเพชรงาม',
    type: 'water',
    location: 'บางบัวทอง นนทบุรี',
    machineCount: 3,
    installDate: '2024-03-10',
    status: 'published',
    description: 'ติดตั้งตู้น้ำ 3 จุดในโครงการหมู่บ้าน รองรับผู้อยู่อาศัย 500 ครัวเรือน',
  },
  {
    id: 'port-004',
    name: 'ปั๊ม PTT สาขาบางนา',
    type: 'coffee',
    location: 'บางนา กรุงเทพมหานคร',
    machineCount: 2,
    installDate: '2024-04-05',
    status: 'published',
    description: 'ติดตั้งตู้กาแฟอัตโนมัติ 2 ตู้ ให้บริการตลอด 24 ชั่วโมง ยอดขายเฉลี่ย 200 แก้ว/วัน',
  },
  {
    id: 'port-005',
    name: 'โรงพยาบาลกรุงเทพ',
    type: 'water',
    location: 'สีลม กรุงเทพมหานคร',
    machineCount: 5,
    installDate: '2024-05-12',
    status: 'published',
    description: 'ติดตั้งตู้น้ำ 5 จุดในพื้นที่ต่างๆ ของโรงพยาบาล รองรับทั้งบุคลากรและผู้รับบริการ',
  },
  {
    id: 'port-006',
    name: 'อพาร์ตเมนต์ The Base',
    type: 'ice',
    location: 'รัชดาภิเษก กรุงเทพมหานคร',
    machineCount: 2,
    installDate: '2024-06-18',
    status: 'published',
    description: 'ติดตั้งตู้น้ำแข็งหยอดเหรียญ 2 ตู้ บริการผู้เช่า 300 ห้อง มียอดใช้งานสม่ำเสมอทุกวัน',
  },
  {
    id: 'port-007',
    name: 'ตลาดนัดจตุจักร',
    type: 'mixed',
    location: 'จตุจักร กรุงเทพมหานคร',
    machineCount: 6,
    installDate: '2024-08-01',
    status: 'draft',
    description: 'โครงการทดลองติดตั้งในตลาดนัด ยังอยู่ระหว่างการประเมินผล',
  },
  {
    id: 'port-008',
    name: 'มหาวิทยาลัยเกษตรศาสตร์',
    type: 'water',
    location: 'ลาดยาว กรุงเทพมหานคร',
    machineCount: 8,
    installDate: '2024-09-15',
    status: 'draft',
    description: 'โครงการขนาดใหญ่ในมหาวิทยาลัย อยู่ระหว่างการเจรจาสัญญาระยะยาว',
  },
]
