import type { Promotion } from './types'

export const mockPromotions: Promotion[] = [
  {
    id: 'promo-001',
    title: 'แพ็กเกจเริ่มต้นสุดคุ้ม',
    description: 'ตู้น้ำ 1 ตู้ ฟรีค่าติดตั้ง พร้อมรับประกัน 2 ปี และบริการซ่อมบำรุงฟรีตลอดปีแรก',
    badge: 'ยอดนิยม',
    startDate: '2026-06-01',
    endDate: '2026-06-30',
    status: 'active',
    imageLabel: 'ตู้น้ำ SAFE',
    gradient: 'from-blue-700 to-sky-400',
    eyebrow: 'สำหรับผู้เริ่มต้นธุรกิจ',
    headline: 'แพ็กเกจเริ่มต้น\nสุดคุ้ม',
  },
  {
    id: 'promo-002',
    title: 'ลดพิเศษ 20% ตู้กาแฟ',
    description: 'ซื้อตู้กาแฟอัตโนมัติรุ่นใดก็ได้ ลดทันที 20% พร้อมโปรแกรมฝึกอบรมการดูแลรักษาฟรี',
    badge: 'Hot Deal',
    startDate: '2026-05-15',
    endDate: '2026-06-15',
    status: 'active',
    imageLabel: 'ตู้กาแฟ SAFE',
    gradient: 'from-blue-800 to-blue-500',
    eyebrow: 'เฉพาะตู้กาแฟอัตโนมัติ',
    headline: 'ลดพิเศษ\n20%',
  },
  {
    id: 'promo-003',
    title: 'แพ็กเกจครบชุด 3 ตู้',
    description: 'ซื้อตู้ครบ 3 ตู้ขึ้นไป รับส่วนลดพิเศษ 15% พร้อมบริการ Site Survey ฟรีและรับประกันรายได้เดือนแรก',
    startDate: '2026-04-01',
    endDate: '2026-05-31',
    status: 'expired',
    imageLabel: 'แพ็กเกจ 3 ตู้',
    gradient: 'from-slate-700 to-slate-400',
    eyebrow: 'ซื้อหลายตู้ยิ่งคุ้ม',
    headline: 'ครบชุด 3 ตู้\nลด 15%',
  },
  {
    id: 'promo-004',
    title: 'โปรช่วงฤดูร้อน',
    description: 'ฤดูร้อนนี้ลงทุนตู้น้ำแข็งได้ในราคาพิเศษ ฟรีค่าจัดส่งและค่าติดตั้งทั่วกรุงเทพฯ',
    badge: 'ฤดูร้อน',
    startDate: '2026-04-01',
    endDate: '2026-05-31',
    status: 'expired',
    imageLabel: 'ตู้น้ำแข็ง SAFE',
    gradient: 'from-slate-700 to-slate-400',
    eyebrow: 'เฉพาะตู้น้ำแข็ง',
    headline: 'โปรฤดูร้อน\nฟรีติดตั้ง',
  },
  {
    id: 'promo-005',
    title: 'แพ็กเกจ Franchise เริ่มต้น',
    description: 'เริ่มต้นธุรกิจ Franchise ตู้น้ำ SAFE ในราคาพิเศษ พร้อม Training เต็มรูปแบบและ Support ตลอดอายุสัญญา',
    startDate: '2026-07-01',
    endDate: '2026-09-30',
    status: 'scheduled',
    imageLabel: 'SAFE Franchise',
    gradient: 'from-sky-500 to-blue-700',
    eyebrow: 'โอกาสทางธุรกิจ',
    headline: 'SAFE\nFranchise',
  },
  {
    id: 'promo-006',
    title: 'สมาชิกใหม่รับทันที!',
    description: 'ลูกค้าใหม่ที่ลงทะเบียนภายในเดือนนี้ รับส่วนลด 5,000 บาท สำหรับการซื้อตู้น้ำหรือตู้กาแฟ',
    badge: 'New',
    startDate: '2026-06-01',
    endDate: '2026-06-30',
    status: 'active',
    imageLabel: 'สมาชิกใหม่',
    gradient: 'from-blue-600 to-sky-300',
    eyebrow: 'สำหรับลูกค้าใหม่',
    headline: 'สมาชิกใหม่\nรับ 5,000 บาท',
  },
]
